name: peakabu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+5

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_timer_countdown: ^1.0.5
  provider: ^6.0.5
  retrofit: ^4.0.1
  dio: ^5.0.0
  json_annotation: ^4.8.0
  image_picker: ^0.8.6+2
  intl_phone_field: ^3.1.0
  platform_device_id: ^1.0.1
  flutter_secure_storage: ^8.0.0
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  firebase_performance: ^0.9.1
  firebase_analytics: ^10.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  url_launcher: ^6.1.10
  shared_preferences : 2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  retrofit_generator: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Semibold.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
  assets:
    - assets/icons/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
